CVS merge

diff --git a/ns2-gea/ns-2/allinone/install b/ns2-gea/ns-2/allinone/install
--- a/ns2-gea/ns-2/allinone/install
+++ b/ns2-gea/ns-2/allinone/install
@@ -16,7 +16,7 @@
 # WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 #
-# $Header: /cvsroot/nsnam/ns-2/allinone/install,v 1.29 2005/02/03 20:15:00 haldar Exp $
+# $Header: /cvsroot/nsnam/ns-2/allinone/install,v 1.32 2007/08/24 04:25:41 tom_henderson Exp $
 
 die() {
 	echo "$@"  1>&2
@@ -201,17 +201,27 @@ cygwin_tests() {
 
 
 # Package VERSIONs. Change these when releasing new packages
-TCLVER=8.4.5
-TKVER=8.4.5
-OTCLVER=1.9
-TCLCLVER=1.16
-NSVER=2.28
-NAMVER=1.11
+TCLVER=8.4.15
+TKVER=8.4.15
+OTCLVER=1.13
+TCLCLVER=1.19
+NSVER=2.32
+NAMVER=1.13
 XGRAPHVER=12.1
-ZLIBVER=1.1.4
+ZLIBVER=1.2.3
 
 # Get current path
 CUR_PATH=`pwd`
+
+echo "============================================================"
+echo "* Testing for Darwin (OS X) environment"
+echo "============================================================"
+if  [ `uname` = "Darwin" ]; then
+    echo "Darwin detected";
+    DYLD_LIBRARY_PATH=$CUR_PATH/tcl$TCLVER/unix:$CUR_PATH/tk$TKVER/unix:$DYLD_LIBRARY_PATH
+    export DYLD_LIBRARY_PATH
+    test_darwin=true
+fi
 
 # A Cygwin install requires these packages:
 packages_base="gcc gcc-g++ gawk tar gzip make patch perl w32api"
@@ -406,7 +416,7 @@ fi
 
 blame='Tcl is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
-./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tcl8.3.2 configuration failed! Exiting ..."
+./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tcl$TCLVER configuration failed! Exiting ..."
 if make 
 then 
 	echo "tcl$TCLVER make succeeded."
@@ -434,7 +444,7 @@ fi
 
 blame='Tk is not part of the ns project.  Please see www.Scriptics.com
 to see if they have a fix for your platform.'
-./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tk8.3.2 configuration failed! Exiting ..."
+./configure --enable-gcc --disable-shared --prefix=$CUR_PATH || die "tk$TKVER configuration failed! Exiting ..."
 if make 
 then
 	echo "tk$TKVER build succeeded."
@@ -495,7 +505,7 @@ cd ./tclcl-$TCLCLVER
 if  [ "${test_cygwin}" = "true" ]; then
         ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "tclcl-$TCLCLVER configuration failed! Exiting ...";
 else
-        ./configure || die "tclcl-$TCLCLVER configuration failed! Exiting ..."
+        ./configure --with-otcl=../otcl-$OTCLVER || die "tclcl-$TCLCLVER configuration failed! Exiting ..."
 fi
 
 if make
@@ -524,7 +534,7 @@ fi
 if  [ "${test_cygwin}" = "true" ]; then
         ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include || die "Ns configuration failed! Exiting ...";
 else
-        ./configure || die "Ns configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER || die "Ns configuration failed! Exiting ...";
 fi
 
 if make
@@ -544,17 +554,36 @@ echo "============================================================"
 echo "* Build nam-$NAMVER"
 echo "============================================================"
 
+ln -s otcl-$OTCLVER otcl
+ln -s tclcl-$TCLCLVER tclcl
+
 cd ./nam-$NAMVER
+
+# XXX temporary OS X hack
+if  [ "${test_darwin}" = "true" ]; then
+ln -s /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation libcorefoundation.dylib
+fi
 
 if  [ "${test_cygwin}" = "true" ]; then
         ./configure --x-libraries=/usr/X11R6/lib --x-includes=/usr/X11R6/include --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  || die "Nam configuration failed! Exiting ...";
 else
-        ./configure --with-tclcl=$CUR_PATH/tclcl-$TCLCLVER  || die "Nam configuration failed! Exiting ...";
+        ./configure --with-otcl=../otcl-$OTCLVER --with-tclcl=../tclcl-$TCLCLVER || die "Nam configuration failed! Exiting ...";
 fi
 
 if make
 then 
     echo "Nam has been installed successfully."
+elif  [ "${test_darwin}" = "true" ]; then
+    # XXX workaround for OS X nam Tcl/Tk problems
+    echo "Nam make failed! Trying to relink..."
+    echo "g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o random.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.4.15/unix/libtcl8.4.a ../tk8.4.15/unix/libtk8.4.a ../tcl8.4.15/unix/libtclstub8.4.a -L../tclcl-1.19 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation"
+    g++ -o nam tkcompat.o tkUnixInit.o xwd.o netview.o netmodel.o edge.o packet.o node.o main.o trace.o queue.o drop.o animation.o agent.o feature.o route.o transform.o paint.o state.o monitor.o anetmodel.o random.o rng.o view.o graphview.o netgraph.o tracehook.o lan.o psview.o group.o editview.o tag.o address.o animator.o wnetmodel.o nam_stream.o enetmodel.o testview.o parser.o trafficsource.o lossmodel.o queuehandle.o gen/version.o gen/nam_tcl.o  ../tcl8.4.15/unix/libtcl8.4.a ../tk8.4.15/unix/libtk8.4.a ../tcl8.4.15/unix/libtclstub8.4.a -L../tclcl-1.19 -ltclcl -L../otcl -lotcl -L/usr/lib -lz -L/usr/X11R6/lib -lXext -lX11 -lm -L. -lcorefoundation
+    if [ -e nam ]; then
+        echo "Nam relinking succeeded; nam has been installed successfully."
+    else
+        echo "Nam make failed! You may want to tweak the above linker path if libraries are not being picked up successfuly.  Continue ..."
+        echo "See http://www.isi.edu/nsnam/ns-problems.html for problems"
+    fi
 else
     echo "Nam make failed! Continue ..."
     echo "See http://www.isi.edu/nsnam/ns-problems.html for problems"
@@ -598,6 +627,7 @@ else
     echo "Please compile your gt-itm & sgb2ns separately."
 fi
 
+echo ""
 echo "Ns-allinone package has been installed successfully."
 echo "Here are the installation places:"
 echo "tcl$TCLVER:	$CUR_PATH/{bin,include,lib}"
@@ -640,8 +670,6 @@ echo ""
 echo "(2) You MUST put $CUR_PATH/tcl$TCLVER/library into your TCL_LIBRARY environmental"
 echo "    variable. Otherwise ns/nam will complain during startup."
 echo ""
-echo "(3) [OPTIONAL] To save disk space, you can now delete directories tcl$TCLVER "
-echo "    and tk$TKVER. They are now installed under $CUR_PATH/{bin,include,lib}"
 echo ""
 echo "After these steps, you can now run the ns validation suite with"
 echo "cd ns-$NSVER; ./validate"
